name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.14"]
    steps:
      - name: git clone
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.9.29"
          python-version: ${{ matrix.python-version }}

      - name: install the project
        run: uv sync --locked --dev

      - name: handle nextpipe dependency
        run: uv add --editable . --no-sync

      - name: unit tests
        env:
          NEXTMV_API_KEY_NEXTPIPE: ${{ secrets.NEXTMV_API_KEY_NEXTPIPE }}
        run: |
          export NEXTMV_API_KEY=$NEXTMV_API_KEY_NEXTPIPE
          uv run pytest
